version: '3'

services:
  neo4j:
    image: neo4j:4.2
    restart: unless-stopped
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./database/conf:/conf
      - ./database/data:/data
      - ./database/import:/import
      - ./database/logs:/logs
      - ./database/plugins:/plugins
    # environment: 
      # Raise memory limits
      # - NEO4J_dbms_memory_pagecache_size=2G
      # - NEO4J_dbms.memory.heap.initial_size=1G
      # - NEO4J_dbms_memory_heap_max__size=1G