version: '3'

services:
  neo4j:
    image: neo4j:4.2
    restart: unless-stopped
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./database/conf:/var/lib/neo4j/conf
      - ./database/data:/var/lib/neo4j/data
      - ./database/import:/var/lib/neo4j/import
      - ./database/logs:/logs
      - ./database/plugins:/var/lib/neo4j/plugins