apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.service.type: loadbalancer
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: neo4j
  name: neo4j
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: neo4j
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.service.type: loadbalancer
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: neo4j
    spec:
      containers:
        - image: neo4j:4.2
          name: neo4j
          ports:
            - containerPort: 7474
            - containerPort: 7687
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/neo4j/conf
              name: neo4j-claim0
            - mountPath: /var/lib/neo4j/data
              name: neo4j-claim1
            - mountPath: /var/lib/neo4j/import
              name: neo4j-claim2
            - mountPath: /logs
              name: neo4j-claim3
            - mountPath: /var/lib/neo4j/plugins
              name: neo4j-claim4
      restartPolicy: Always
      volumes:
        - name: neo4j-claim0
          persistentVolumeClaim:
            claimName: neo4j-claim0
        - name: neo4j-claim1
          persistentVolumeClaim:
            claimName: neo4j-claim1
        - name: neo4j-claim2
          persistentVolumeClaim:
            claimName: neo4j-claim2
        - name: neo4j-claim3
          persistentVolumeClaim:
            claimName: neo4j-claim3
        - name: neo4j-claim4
          persistentVolumeClaim:
            claimName: neo4j-claim4
status: {}
